---
# tasks file for prod
- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - docker.io
    - mc

- name: Create Docker container
  docker_container:
    name: prod server
    build:
      dockerfile: Dockerfile
      volemes: /home:/opt/tomcat/webapps/